core:
  hot_reload: false
  websocket_connections:
#    - self_ids: [ '10271142164762155356', '211134009' ]   # 平台账号，可填写一个/多个
#      address: '124.221.153.148:5141/satori/v1'   # 主机地址 与 path路径 与 版本
#      token: 'tmrn' # 由前端提供

    - self_ids: [ '211134009' ]   # 平台账号，可填写一个/多个
  #    为什么不用填平台，因为 self_ids 在这里的作用是仅通此值寻找唯一 address
      address: '124.221.153.148:5501/v1'   # 主机地址 与 path路径 与 版本
      token: 'f7e840aa7f4da1cb71ba943a8bbb3de0fc914e3a10e3b50322b3093bb24ab695' # 由前端提供
#
#    - self_ids: [ '102057960', '211134009', '821784147' ]   # 平台账号，可填写一个/多个
#      address: '124.221.153.148:5141/satori/v1'   # 主机地址 与 path路径 与 版本
#      token: 'tmrn' # 由前端提供
