# WS 配置
connections:
  - self_id: '114514' # 平台账号1
    url: 'ws://127.0.0.1:5140/satori' # websockets 连接 前端 的 url (可能包含/path)
    endpoint: 'http://127.0.0.1:5140/satori' # http 连接 前端 的 url (可能包含/path)
    token: 'your_token'
    version: 'v1'
    HeartbeatInterval: 5 # 心跳间隔 < 10 ，单位秒

#  - self_id: '1919810' # 平台账号2
#    url...

# DEV 开发模式 配置 =======================================
dev:
  endpoint: 'http://127.0.0.1:17240/'  # dev 模式用与连接 flask 的url
  port: '17240'  # 和上面一样
