core:
  plugins-dir:
    - path: 'plugins_i_write'
      priority: 1
    - path: 'plugins'
      priority: 4

auth:
  - platform: 'red'
    admin: ['114514']
  - platform: 'onebot'
    admin: [ '1919810' ]

message_content_tools:
  prefix: ['-']  #  指令前缀


websocket_client:
  connections:
    - self_ids: [ '11111', '22222' ]   # 平台账号，可填写一个/多个
      link_way: 'websocket'
      address: '127.0.0.1:5140/satori/v1'   # 主机地址 与 path路径 与 版本
      http_protocol: 'http' # 这个选可以不填，默认http
      token: 'Your_token' # 由前端提供

    - self_ids: [ '33333' ]
      link_way: 'webhook'
      address: '127.0.0.1:5140/satori/v1'
      token: 'Your_token'






